#!/usr/bin/env python3

import sys
sys.path.append('lib')

from charms.reactive import is_state
from charmhelpers.core import hookenv
from charms.layer.hadoop_base import get_hadoop_base
from jujubigdata.handlers import HDFS


hadoop = is_state('hadoop.installed')
leader = is_state('leadership.is_leader')
ha = is_state('leadership.set.ha-initialized')

if not hadoop or not (leader or ha):
    hookenv.action_fail('NameNode not yet ready')
    sys.exit()

HDFS(get_hadoop_base()).start_namenode()
