#!/bin/bash

if ! charms.reactive is_state 'namenode.ready'; then
    action-fail 'NameNode not yet ready'
    exit
fi

if command -v systemctl >/dev/null; then
  # assume systemd
  systemctl stop namenode
elif command -v service >/dev/null; then
  # assume upstart
  service namenode stop
fi
