#!/usr/bin/env python3

import sys
sys.path.append('lib')

from charms.reactive import is_state
from charms.layer.hadoop_base import get_hadoop_base
from jujubigdata.handlers import HDFS

if not is_state('namenode.ready'):
    sys.exit()

HDFS(get_hadoop_base()).stop_namenode()
